apiVersion: v1
kind: Service
metadata:
  name: mi-app-servicio
  namespace: produccion-real
spec:
  type: LoadBalancer
  selector:
    app: mi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
